# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGui2.ui'
#
# Created: Tue May 27 00:26:29 2014
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainDialog(object):
    def setupUi(self, mainDialog):
        mainDialog.setObjectName("mainDialog")
        mainDialog.resize(940, 639)
        mainDialog.setStyleSheet("")
        self.frame = QtGui.QFrame(mainDialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 941, 641))
        self.frame.setStyleSheet("\n"
"QFrame{\n"
"font: 12pt \"Calibri\";\n"
"background-color: rgb(208, 208, 208);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"\n"
"}\n"
"QToolButton{\n"
"font: 12pt \"Calibri\";\n"
"}")
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBoxInfo = QtGui.QGroupBox(self.frame)
        self.groupBoxInfo.setGeometry(QtCore.QRect(20, 160, 211, 271))
        self.groupBoxInfo.setStyleSheet("font: 12pt \"Calibri\";")
        self.groupBoxInfo.setFlat(False)
        self.groupBoxInfo.setObjectName("groupBoxInfo")
        self.qlTech = QtGui.QLabel(self.groupBoxInfo)
        self.qlTech.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.qlTech.setObjectName("qlTech")
        self.comboBoxTech = QtGui.QComboBox(self.groupBoxInfo)
        self.comboBoxTech.setGeometry(QtCore.QRect(100, 30, 101, 22))
        self.comboBoxTech.setObjectName("comboBoxTech")
        self.qlBand = QtGui.QLabel(self.groupBoxInfo)
        self.qlBand.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.qlBand.setObjectName("qlBand")
        self.comboBoxBand = QtGui.QComboBox(self.groupBoxInfo)
        self.comboBoxBand.setGeometry(QtCore.QRect(100, 60, 101, 22))
        self.comboBoxBand.setObjectName("comboBoxBand")
        self.qlDLchTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlDLchTitle.setGeometry(QtCore.QRect(10, 120, 81, 21))
        self.qlDLchTitle.setObjectName("qlDLchTitle")
        self.qlULchTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlULchTitle.setGeometry(QtCore.QRect(10, 150, 81, 21))
        self.qlULchTitle.setObjectName("qlULchTitle")
        self.qlPDMTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlPDMTitle.setGeometry(QtCore.QRect(10, 180, 81, 21))
        self.qlPDMTitle.setObjectName("qlPDMTitle")
        self.qlSMPSTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlSMPSTitle.setGeometry(QtCore.QRect(10, 210, 81, 21))
        self.qlSMPSTitle.setObjectName("qlSMPSTitle")
        self.qlBWTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlBWTitle.setGeometry(QtCore.QRect(10, 90, 81, 21))
        self.qlBWTitle.setObjectName("qlBWTitle")
        self.qlBW = QtGui.QLabel(self.groupBoxInfo)
        self.qlBW.setGeometry(QtCore.QRect(120, 90, 81, 21))
        self.qlBW.setStyleSheet("")
        self.qlBW.setObjectName("qlBW")
        self.qlDLch = QtGui.QLabel(self.groupBoxInfo)
        self.qlDLch.setGeometry(QtCore.QRect(120, 120, 81, 21))
        self.qlDLch.setObjectName("qlDLch")
        self.qlULch = QtGui.QLabel(self.groupBoxInfo)
        self.qlULch.setGeometry(QtCore.QRect(120, 150, 81, 21))
        self.qlULch.setObjectName("qlULch")
        self.qlICQTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlICQTitle.setGeometry(QtCore.QRect(10, 240, 81, 21))
        self.qlICQTitle.setObjectName("qlICQTitle")
        self.qlePDM = QtGui.QLineEdit(self.groupBoxInfo)
        self.qlePDM.setGeometry(QtCore.QRect(100, 180, 51, 20))
        self.qlePDM.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qlePDM.setMaxLength(3)
        self.qlePDM.setAlignment(QtCore.Qt.AlignCenter)
        self.qlePDM.setObjectName("qlePDM")
        self.btnSetPDM = QtGui.QToolButton(self.groupBoxInfo)
        self.btnSetPDM.setGeometry(QtCore.QRect(160, 180, 41, 21))
        self.btnSetPDM.setObjectName("btnSetPDM")
        self.qleSMPS = QtGui.QLineEdit(self.groupBoxInfo)
        self.qleSMPS.setGeometry(QtCore.QRect(100, 210, 51, 20))
        self.qleSMPS.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qleSMPS.setMaxLength(4)
        self.qleSMPS.setAlignment(QtCore.Qt.AlignCenter)
        self.qleSMPS.setObjectName("qleSMPS")
        self.btnSetSMPS = QtGui.QToolButton(self.groupBoxInfo)
        self.btnSetSMPS.setGeometry(QtCore.QRect(160, 210, 41, 21))
        self.btnSetSMPS.setObjectName("btnSetSMPS")
        self.qleICQ = QtGui.QLineEdit(self.groupBoxInfo)
        self.qleICQ.setGeometry(QtCore.QRect(100, 240, 51, 20))
        self.qleICQ.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qleICQ.setMaxLength(2)
        self.qleICQ.setAlignment(QtCore.Qt.AlignCenter)
        self.qleICQ.setObjectName("qleICQ")
        self.btnSetICQ = QtGui.QToolButton(self.groupBoxInfo)
        self.btnSetICQ.setGeometry(QtCore.QRect(160, 240, 41, 21))
        self.btnSetICQ.setObjectName("btnSetICQ")
        self.groupBoxSweep = QtGui.QGroupBox(self.frame)
        self.groupBoxSweep.setGeometry(QtCore.QRect(20, 450, 211, 151))
        self.groupBoxSweep.setStyleSheet("font: 12pt \"Calibri\";")
        self.groupBoxSweep.setObjectName("groupBoxSweep")
        self.qlSweepPDMStart = QtGui.QLabel(self.groupBoxSweep)
        self.qlSweepPDMStart.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.qlSweepPDMStart.setObjectName("qlSweepPDMStart")
        self.qlSweepPDMEnd = QtGui.QLabel(self.groupBoxSweep)
        self.qlSweepPDMEnd.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.qlSweepPDMEnd.setObjectName("qlSweepPDMEnd")
        self.spinBoxPDMStart = QtGui.QSpinBox(self.groupBoxSweep)
        self.spinBoxPDMStart.setGeometry(QtCore.QRect(110, 30, 71, 22))
        self.spinBoxPDMStart.setObjectName("spinBoxPDMStart")
        self.spinBoxPDMEnd = QtGui.QSpinBox(self.groupBoxSweep)
        self.spinBoxPDMEnd.setGeometry(QtCore.QRect(110, 60, 71, 22))
        self.spinBoxPDMEnd.setObjectName("spinBoxPDMEnd")
        self.btnStartSweep = QtGui.QToolButton(self.groupBoxSweep)
        self.btnStartSweep.setGeometry(QtCore.QRect(50, 100, 91, 31))
        self.btnStartSweep.setObjectName("btnStartSweep")
        self.btnChMinus = QtGui.QToolButton(self.frame)
        self.btnChMinus.setGeometry(QtCore.QRect(470, 500, 61, 61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnChMinus.setIcon(icon)
        self.btnChMinus.setIconSize(QtCore.QSize(32, 32))
        self.btnChMinus.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnChMinus.setObjectName("btnChMinus")
        self.btnPDMPlus = QtGui.QToolButton(self.frame)
        self.btnPDMPlus.setGeometry(QtCore.QRect(540, 460, 61, 61))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPDMPlus.setIcon(icon1)
        self.btnPDMPlus.setIconSize(QtCore.QSize(32, 32))
        self.btnPDMPlus.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPDMPlus.setObjectName("btnPDMPlus")
        self.btnChPlus = QtGui.QToolButton(self.frame)
        self.btnChPlus.setGeometry(QtCore.QRect(610, 500, 61, 61))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnChPlus.setIcon(icon2)
        self.btnChPlus.setIconSize(QtCore.QSize(32, 32))
        self.btnChPlus.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnChPlus.setObjectName("btnChPlus")
        self.btnPDMMinus = QtGui.QToolButton(self.frame)
        self.btnPDMMinus.setGeometry(QtCore.QRect(540, 540, 61, 61))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPDMMinus.setIcon(icon3)
        self.btnPDMMinus.setIconSize(QtCore.QSize(32, 32))
        self.btnPDMMinus.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPDMMinus.setObjectName("btnPDMMinus")
        self.groupBoxMisc = QtGui.QGroupBox(self.frame)
        self.groupBoxMisc.setGeometry(QtCore.QRect(20, 20, 211, 131))
        self.groupBoxMisc.setStyleSheet("font: 12pt \"Calibri\";")
        self.groupBoxMisc.setObjectName("groupBoxMisc")
        self.qlGPIBTitle = QtGui.QLabel(self.groupBoxMisc)
        self.qlGPIBTitle.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.qlGPIBTitle.setObjectName("qlGPIBTitle")
        self.qlCOMTitle = QtGui.QLabel(self.groupBoxMisc)
        self.qlCOMTitle.setGeometry(QtCore.QRect(10, 90, 81, 21))
        self.qlCOMTitle.setObjectName("qlCOMTitle")
        self.qlGPIBTitle_2 = QtGui.QLabel(self.groupBoxMisc)
        self.qlGPIBTitle_2.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.qlGPIBTitle_2.setObjectName("qlGPIBTitle_2")
        self.qleGPIB = QtGui.QLineEdit(self.groupBoxMisc)
        self.qleGPIB.setGeometry(QtCore.QRect(110, 30, 41, 20))
        self.qleGPIB.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qleGPIB.setMaxLength(3)
        self.qleGPIB.setAlignment(QtCore.Qt.AlignCenter)
        self.qleGPIB.setObjectName("qleGPIB")
        self.btnSetGPIB = QtGui.QToolButton(self.groupBoxMisc)
        self.btnSetGPIB.setGeometry(QtCore.QRect(160, 30, 41, 21))
        self.btnSetGPIB.setObjectName("btnSetGPIB")
        self.qleGPIB_2 = QtGui.QLineEdit(self.groupBoxMisc)
        self.qleGPIB_2.setGeometry(QtCore.QRect(110, 60, 41, 20))
        self.qleGPIB_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qleGPIB_2.setMaxLength(3)
        self.qleGPIB_2.setAlignment(QtCore.Qt.AlignCenter)
        self.qleGPIB_2.setObjectName("qleGPIB_2")
        self.btnSetGPIB_2 = QtGui.QToolButton(self.groupBoxMisc)
        self.btnSetGPIB_2.setGeometry(QtCore.QRect(160, 60, 41, 21))
        self.btnSetGPIB_2.setObjectName("btnSetGPIB_2")
        self.qleCOM = QtGui.QLineEdit(self.groupBoxMisc)
        self.qleCOM.setGeometry(QtCore.QRect(110, 90, 41, 20))
        self.qleCOM.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qleCOM.setMaxLength(3)
        self.qleCOM.setAlignment(QtCore.Qt.AlignCenter)
        self.qleCOM.setObjectName("qleCOM")
        self.btnSetCOM = QtGui.QToolButton(self.groupBoxMisc)
        self.btnSetCOM.setGeometry(QtCore.QRect(160, 90, 41, 21))
        self.btnSetCOM.setObjectName("btnSetCOM")
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(250, 460, 101, 111))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnHPM = QtGui.QToolButton(self.frame_2)
        self.btnHPM.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.btnHPM.setCheckable(True)
        self.btnHPM.setAutoExclusive(True)
        self.btnHPM.setObjectName("btnHPM")
        self.btnLPM = QtGui.QToolButton(self.frame_2)
        self.btnLPM.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.btnLPM.setCheckable(True)
        self.btnLPM.setAutoExclusive(True)
        self.btnLPM.setObjectName("btnLPM")
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(350, 460, 111, 111))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btnTxOff = QtGui.QToolButton(self.frame_3)
        self.btnTxOff.setGeometry(QtCore.QRect(10, 60, 91, 31))
        self.btnTxOff.setCheckable(True)
        self.btnTxOff.setAutoExclusive(True)
        self.btnTxOff.setObjectName("btnTxOff")
        self.btnTxOn = QtGui.QToolButton(self.frame_3)
        self.btnTxOn.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.btnTxOn.setCheckable(True)
        self.btnTxOn.setAutoExclusive(True)
        self.btnTxOn.setObjectName("btnTxOn")
        self.tableWidget = QtGui.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(250, 50, 641, 391))
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget.setStyleSheet("font: 10pt \"Calibri\";\n"
"background-color: rgb(225, 225, 225);")
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(15)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.qlMessage = QtGui.QLabel(self.frame)
        self.qlMessage.setGeometry(QtCore.QRect(260, 20, 591, 16))
        self.qlMessage.setObjectName("qlMessage")
        self.groupBoxSMPSStep = QtGui.QGroupBox(self.frame)
        self.groupBoxSMPSStep.setGeometry(QtCore.QRect(690, 460, 101, 141))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.groupBoxSMPSStep.setFont(font)
        self.groupBoxSMPSStep.setObjectName("groupBoxSMPSStep")
        self.qleSMPSStep = QtGui.QLineEdit(self.groupBoxSMPSStep)
        self.qleSMPSStep.setGeometry(QtCore.QRect(10, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.qleSMPSStep.setFont(font)
        self.qleSMPSStep.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qleSMPSStep.setMaxLength(4)
        self.qleSMPSStep.setAlignment(QtCore.Qt.AlignCenter)
        self.qleSMPSStep.setObjectName("qleSMPSStep")
        self.btnSMPSPlus = QtGui.QToolButton(self.groupBoxSMPSStep)
        self.btnSMPSPlus.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.btnSMPSPlus.setObjectName("btnSMPSPlus")
        self.btnSMPSMinus = QtGui.QToolButton(self.groupBoxSMPSStep)
        self.btnSMPSMinus.setGeometry(QtCore.QRect(10, 100, 81, 31))
        self.btnSMPSMinus.setObjectName("btnSMPSMinus")
        self.groupBoxICQStep = QtGui.QGroupBox(self.frame)
        self.groupBoxICQStep.setGeometry(QtCore.QRect(800, 460, 101, 141))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.groupBoxICQStep.setFont(font)
        self.groupBoxICQStep.setObjectName("groupBoxICQStep")
        self.qleICQStep = QtGui.QLineEdit(self.groupBoxICQStep)
        self.qleICQStep.setGeometry(QtCore.QRect(10, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.qleICQStep.setFont(font)
        self.qleICQStep.setInputMethodHints(QtCore.Qt.ImhNone)
        self.qleICQStep.setMaxLength(2)
        self.qleICQStep.setAlignment(QtCore.Qt.AlignCenter)
        self.qleICQStep.setObjectName("qleICQStep")
        self.btnICQPlus = QtGui.QToolButton(self.groupBoxICQStep)
        self.btnICQPlus.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.btnICQPlus.setObjectName("btnICQPlus")
        self.btnICQMinus = QtGui.QToolButton(self.groupBoxICQStep)
        self.btnICQMinus.setGeometry(QtCore.QRect(10, 100, 81, 31))
        self.btnICQMinus.setObjectName("btnICQMinus")
        self.actionCopy = QtGui.QAction(mainDialog)
        self.actionCopy.setObjectName("actionCopy")

        self.retranslateUi(mainDialog)
        QtCore.QMetaObject.connectSlotsByName(mainDialog)
        mainDialog.setTabOrder(self.comboBoxTech, self.comboBoxBand)
        mainDialog.setTabOrder(self.comboBoxBand, self.spinBoxPDMStart)
        mainDialog.setTabOrder(self.spinBoxPDMStart, self.spinBoxPDMEnd)
        mainDialog.setTabOrder(self.spinBoxPDMEnd, self.btnStartSweep)
        mainDialog.setTabOrder(self.btnStartSweep, self.btnHPM)
        mainDialog.setTabOrder(self.btnHPM, self.btnLPM)
        mainDialog.setTabOrder(self.btnLPM, self.btnTxOn)
        mainDialog.setTabOrder(self.btnTxOn, self.btnTxOff)
        mainDialog.setTabOrder(self.btnTxOff, self.btnChMinus)
        mainDialog.setTabOrder(self.btnChMinus, self.btnChPlus)
        mainDialog.setTabOrder(self.btnChPlus, self.btnPDMPlus)
        mainDialog.setTabOrder(self.btnPDMPlus, self.btnPDMMinus)

    def retranslateUi(self, mainDialog):
        mainDialog.setWindowTitle(QtGui.QApplication.translate("mainDialog", "RF Tuning Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxInfo.setTitle(QtGui.QApplication.translate("mainDialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.qlTech.setText(QtGui.QApplication.translate("mainDialog", "Technology", None, QtGui.QApplication.UnicodeUTF8))
        self.qlBand.setText(QtGui.QApplication.translate("mainDialog", "Band", None, QtGui.QApplication.UnicodeUTF8))
        self.qlDLchTitle.setText(QtGui.QApplication.translate("mainDialog", "DL channel", None, QtGui.QApplication.UnicodeUTF8))
        self.qlULchTitle.setText(QtGui.QApplication.translate("mainDialog", "UL channel", None, QtGui.QApplication.UnicodeUTF8))
        self.qlPDMTitle.setText(QtGui.QApplication.translate("mainDialog", "PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.qlSMPSTitle.setText(QtGui.QApplication.translate("mainDialog", "SMPS", None, QtGui.QApplication.UnicodeUTF8))
        self.qlBWTitle.setText(QtGui.QApplication.translate("mainDialog", "Bandwidth", None, QtGui.QApplication.UnicodeUTF8))
        self.qlBW.setText(QtGui.QApplication.translate("mainDialog", "5MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.qlDLch.setText(QtGui.QApplication.translate("mainDialog", "10700", None, QtGui.QApplication.UnicodeUTF8))
        self.qlULch.setText(QtGui.QApplication.translate("mainDialog", "9750", None, QtGui.QApplication.UnicodeUTF8))
        self.qlICQTitle.setText(QtGui.QApplication.translate("mainDialog", "ICQ", None, QtGui.QApplication.UnicodeUTF8))
        self.qlePDM.setInputMask(QtGui.QApplication.translate("mainDialog", "000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.qlePDM.setText(QtGui.QApplication.translate("mainDialog", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetPDM.setText(QtGui.QApplication.translate("mainDialog", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.qleSMPS.setInputMask(QtGui.QApplication.translate("mainDialog", "0000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.qleSMPS.setText(QtGui.QApplication.translate("mainDialog", "3400", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetSMPS.setText(QtGui.QApplication.translate("mainDialog", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.qleICQ.setInputMask(QtGui.QApplication.translate("mainDialog", "hh; ", None, QtGui.QApplication.UnicodeUTF8))
        self.qleICQ.setText(QtGui.QApplication.translate("mainDialog", "BC", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetICQ.setText(QtGui.QApplication.translate("mainDialog", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSweep.setTitle(QtGui.QApplication.translate("mainDialog", "Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.qlSweepPDMStart.setText(QtGui.QApplication.translate("mainDialog", "Start PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.qlSweepPDMEnd.setText(QtGui.QApplication.translate("mainDialog", "End PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStartSweep.setText(QtGui.QApplication.translate("mainDialog", "Start Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChMinus.setText(QtGui.QApplication.translate("mainDialog", "-ch", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChMinus.setShortcut(QtGui.QApplication.translate("mainDialog", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPDMPlus.setText(QtGui.QApplication.translate("mainDialog", "+PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPDMPlus.setShortcut(QtGui.QApplication.translate("mainDialog", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChPlus.setText(QtGui.QApplication.translate("mainDialog", "+ch", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChPlus.setShortcut(QtGui.QApplication.translate("mainDialog", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPDMMinus.setText(QtGui.QApplication.translate("mainDialog", "-PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPDMMinus.setShortcut(QtGui.QApplication.translate("mainDialog", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxMisc.setTitle(QtGui.QApplication.translate("mainDialog", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.qlGPIBTitle.setText(QtGui.QApplication.translate("mainDialog", "Callbox GPIB", None, QtGui.QApplication.UnicodeUTF8))
        self.qlCOMTitle.setText(QtGui.QApplication.translate("mainDialog", "Phone COM", None, QtGui.QApplication.UnicodeUTF8))
        self.qlGPIBTitle_2.setText(QtGui.QApplication.translate("mainDialog", "Power Supply", None, QtGui.QApplication.UnicodeUTF8))
        self.qleGPIB.setInputMask(QtGui.QApplication.translate("mainDialog", "000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.qleGPIB.setText(QtGui.QApplication.translate("mainDialog", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetGPIB.setText(QtGui.QApplication.translate("mainDialog", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.qleGPIB_2.setInputMask(QtGui.QApplication.translate("mainDialog", "000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.qleGPIB_2.setText(QtGui.QApplication.translate("mainDialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetGPIB_2.setText(QtGui.QApplication.translate("mainDialog", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.qleCOM.setInputMask(QtGui.QApplication.translate("mainDialog", "000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.qleCOM.setText(QtGui.QApplication.translate("mainDialog", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetCOM.setText(QtGui.QApplication.translate("mainDialog", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHPM.setText(QtGui.QApplication.translate("mainDialog", "HPM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLPM.setText(QtGui.QApplication.translate("mainDialog", "LPM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTxOff.setText(QtGui.QApplication.translate("mainDialog", "Tx OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTxOn.setText(QtGui.QApplication.translate("mainDialog", "Tx ON", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("mainDialog", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("mainDialog", "Tx power", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("mainDialog", "PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("mainDialog", "Max curr", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("mainDialog", "min curr", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("mainDialog", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("mainDialog", "-5MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("mainDialog", "+5MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("mainDialog", "EURTA-1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("mainDialog", "EUTRA+1", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 0).setText(QtGui.QApplication.translate("mainDialog", "9750", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.qlMessage.setText(QtGui.QApplication.translate("mainDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSMPSStep.setTitle(QtGui.QApplication.translate("mainDialog", "SMPS Step", None, QtGui.QApplication.UnicodeUTF8))
        self.qleSMPSStep.setInputMask(QtGui.QApplication.translate("mainDialog", "0000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.qleSMPSStep.setText(QtGui.QApplication.translate("mainDialog", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSMPSPlus.setText(QtGui.QApplication.translate("mainDialog", "+SMPS", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSMPSMinus.setText(QtGui.QApplication.translate("mainDialog", "-SMPS", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxICQStep.setTitle(QtGui.QApplication.translate("mainDialog", "ICQ Step", None, QtGui.QApplication.UnicodeUTF8))
        self.qleICQStep.setInputMask(QtGui.QApplication.translate("mainDialog", "hh; ", None, QtGui.QApplication.UnicodeUTF8))
        self.qleICQStep.setText(QtGui.QApplication.translate("mainDialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.btnICQPlus.setText(QtGui.QApplication.translate("mainDialog", "+ICQ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnICQMinus.setText(QtGui.QApplication.translate("mainDialog", "-ICQ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("mainDialog", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("mainDialog", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))

import icon_rc
