# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGui_2.ui'
#
# Created: Mon Aug 19 15:01:50 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainDialog(object):
    def setupUi(self, mainDialog):
        mainDialog.setObjectName("mainDialog")
        mainDialog.resize(940, 639)
        mainDialog.setStyleSheet("")
        self.frame = QtGui.QFrame(mainDialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 941, 641))
        self.frame.setStyleSheet("\n"
"QFrame{\n"
"font: 12pt \"Calibri\";\n"
"background-color: rgb(208, 208, 208);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"\n"
"}\n"
"QToolButton{\n"
"font: 12pt \"Calibri\";\n"
"}")
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBoxInfo = QtGui.QGroupBox(self.frame)
        self.groupBoxInfo.setGeometry(QtCore.QRect(20, 10, 211, 261))
        self.groupBoxInfo.setStyleSheet("font: 12pt \"Calibri\";")
        self.groupBoxInfo.setFlat(False)
        self.groupBoxInfo.setObjectName("groupBoxInfo")
        self.qlTech = QtGui.QLabel(self.groupBoxInfo)
        self.qlTech.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.qlTech.setObjectName("qlTech")
        self.comboBoxTech = QtGui.QComboBox(self.groupBoxInfo)
        self.comboBoxTech.setGeometry(QtCore.QRect(110, 30, 91, 22))
        self.comboBoxTech.setObjectName("comboBoxTech")
        self.qlBand = QtGui.QLabel(self.groupBoxInfo)
        self.qlBand.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.qlBand.setObjectName("qlBand")
        self.comboBoxBand = QtGui.QComboBox(self.groupBoxInfo)
        self.comboBoxBand.setGeometry(QtCore.QRect(110, 60, 91, 22))
        self.comboBoxBand.setObjectName("comboBoxBand")
        self.qlDLchTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlDLchTitle.setGeometry(QtCore.QRect(10, 120, 81, 21))
        self.qlDLchTitle.setObjectName("qlDLchTitle")
        self.qlULchTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlULchTitle.setGeometry(QtCore.QRect(10, 150, 81, 21))
        self.qlULchTitle.setObjectName("qlULchTitle")
        self.qlPDMTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlPDMTitle.setGeometry(QtCore.QRect(10, 180, 81, 21))
        self.qlPDMTitle.setObjectName("qlPDMTitle")
        self.qlSMPSTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlSMPSTitle.setGeometry(QtCore.QRect(10, 210, 81, 21))
        self.qlSMPSTitle.setObjectName("qlSMPSTitle")
        self.qlBWTitle = QtGui.QLabel(self.groupBoxInfo)
        self.qlBWTitle.setGeometry(QtCore.QRect(10, 90, 81, 21))
        self.qlBWTitle.setObjectName("qlBWTitle")
        self.qlBW = QtGui.QLabel(self.groupBoxInfo)
        self.qlBW.setGeometry(QtCore.QRect(120, 90, 81, 21))
        self.qlBW.setStyleSheet("")
        self.qlBW.setObjectName("qlBW")
        self.qlDLch = QtGui.QLabel(self.groupBoxInfo)
        self.qlDLch.setGeometry(QtCore.QRect(120, 120, 81, 21))
        self.qlDLch.setObjectName("qlDLch")
        self.qlULch = QtGui.QLabel(self.groupBoxInfo)
        self.qlULch.setGeometry(QtCore.QRect(120, 150, 81, 21))
        self.qlULch.setObjectName("qlULch")
        self.qlPDM = QtGui.QLabel(self.groupBoxInfo)
        self.qlPDM.setGeometry(QtCore.QRect(120, 180, 81, 21))
        self.qlPDM.setObjectName("qlPDM")
        self.qlSMPS = QtGui.QLabel(self.groupBoxInfo)
        self.qlSMPS.setGeometry(QtCore.QRect(120, 210, 81, 21))
        self.qlSMPS.setObjectName("qlSMPS")
        self.groupBoxSweep = QtGui.QGroupBox(self.frame)
        self.groupBoxSweep.setGeometry(QtCore.QRect(20, 450, 211, 151))
        self.groupBoxSweep.setStyleSheet("font: 12pt \"Calibri\";")
        self.groupBoxSweep.setObjectName("groupBoxSweep")
        self.qlSweepPDMStart = QtGui.QLabel(self.groupBoxSweep)
        self.qlSweepPDMStart.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.qlSweepPDMStart.setObjectName("qlSweepPDMStart")
        self.qlSweepPDMEnd = QtGui.QLabel(self.groupBoxSweep)
        self.qlSweepPDMEnd.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.qlSweepPDMEnd.setObjectName("qlSweepPDMEnd")
        self.spinBoxPDMStart = QtGui.QSpinBox(self.groupBoxSweep)
        self.spinBoxPDMStart.setGeometry(QtCore.QRect(110, 30, 71, 22))
        self.spinBoxPDMStart.setObjectName("spinBoxPDMStart")
        self.spinBoxPDMEnd = QtGui.QSpinBox(self.groupBoxSweep)
        self.spinBoxPDMEnd.setGeometry(QtCore.QRect(110, 60, 71, 22))
        self.spinBoxPDMEnd.setObjectName("spinBoxPDMEnd")
        self.btnStartSweep = QtGui.QToolButton(self.groupBoxSweep)
        self.btnStartSweep.setGeometry(QtCore.QRect(50, 100, 91, 31))
        self.btnStartSweep.setObjectName("btnStartSweep")
        self.btnChMinus = QtGui.QToolButton(self.frame)
        self.btnChMinus.setGeometry(QtCore.QRect(560, 500, 61, 61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnChMinus.setIcon(icon)
        self.btnChMinus.setIconSize(QtCore.QSize(32, 32))
        self.btnChMinus.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnChMinus.setObjectName("btnChMinus")
        self.btnPDMPlus = QtGui.QToolButton(self.frame)
        self.btnPDMPlus.setGeometry(QtCore.QRect(630, 460, 61, 61))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPDMPlus.setIcon(icon1)
        self.btnPDMPlus.setIconSize(QtCore.QSize(32, 32))
        self.btnPDMPlus.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPDMPlus.setObjectName("btnPDMPlus")
        self.btnChPlus = QtGui.QToolButton(self.frame)
        self.btnChPlus.setGeometry(QtCore.QRect(700, 500, 61, 61))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnChPlus.setIcon(icon2)
        self.btnChPlus.setIconSize(QtCore.QSize(32, 32))
        self.btnChPlus.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnChPlus.setObjectName("btnChPlus")
        self.btnPDMMinus = QtGui.QToolButton(self.frame)
        self.btnPDMMinus.setGeometry(QtCore.QRect(630, 540, 61, 61))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPDMMinus.setIcon(icon3)
        self.btnPDMMinus.setIconSize(QtCore.QSize(32, 32))
        self.btnPDMMinus.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnPDMMinus.setObjectName("btnPDMMinus")
        self.groupBoxMisc = QtGui.QGroupBox(self.frame)
        self.groupBoxMisc.setGeometry(QtCore.QRect(20, 290, 211, 141))
        self.groupBoxMisc.setStyleSheet("font: 12pt \"Calibri\";")
        self.groupBoxMisc.setObjectName("groupBoxMisc")
        self.qlGPIBTitle = QtGui.QLabel(self.groupBoxMisc)
        self.qlGPIBTitle.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.qlGPIBTitle.setObjectName("qlGPIBTitle")
        self.qlCOMTitle = QtGui.QLabel(self.groupBoxMisc)
        self.qlCOMTitle.setGeometry(QtCore.QRect(10, 90, 81, 21))
        self.qlCOMTitle.setObjectName("qlCOMTitle")
        self.qlGPIB = QtGui.QLabel(self.groupBoxMisc)
        self.qlGPIB.setGeometry(QtCore.QRect(120, 30, 81, 21))
        self.qlGPIB.setObjectName("qlGPIB")
        self.qlCOM = QtGui.QLabel(self.groupBoxMisc)
        self.qlCOM.setGeometry(QtCore.QRect(120, 90, 81, 21))
        self.qlCOM.setObjectName("qlCOM")
        self.qlGPIBTitle_2 = QtGui.QLabel(self.groupBoxMisc)
        self.qlGPIBTitle_2.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.qlGPIBTitle_2.setObjectName("qlGPIBTitle_2")
        self.qlGPIB_2 = QtGui.QLabel(self.groupBoxMisc)
        self.qlGPIB_2.setGeometry(QtCore.QRect(120, 60, 81, 21))
        self.qlGPIB_2.setObjectName("qlGPIB_2")
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(260, 460, 121, 111))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnHPM = QtGui.QToolButton(self.frame_2)
        self.btnHPM.setGeometry(QtCore.QRect(20, 20, 81, 31))
        self.btnHPM.setCheckable(True)
        self.btnHPM.setAutoExclusive(True)
        self.btnHPM.setObjectName("btnHPM")
        self.btnLPM = QtGui.QToolButton(self.frame_2)
        self.btnLPM.setGeometry(QtCore.QRect(20, 60, 81, 31))
        self.btnLPM.setCheckable(True)
        self.btnLPM.setAutoExclusive(True)
        self.btnLPM.setObjectName("btnLPM")
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(400, 460, 121, 111))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btnTxOff = QtGui.QToolButton(self.frame_3)
        self.btnTxOff.setGeometry(QtCore.QRect(10, 60, 91, 31))
        self.btnTxOff.setCheckable(True)
        self.btnTxOff.setAutoExclusive(True)
        self.btnTxOff.setObjectName("btnTxOff")
        self.btnTxOn = QtGui.QToolButton(self.frame_3)
        self.btnTxOn.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.btnTxOn.setCheckable(True)
        self.btnTxOn.setAutoExclusive(True)
        self.btnTxOn.setObjectName("btnTxOn")
        self.tableWidget = QtGui.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(250, 50, 641, 391))
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget.setStyleSheet("font: 10pt \"Calibri\";\n"
"background-color: rgb(225, 225, 225);")
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(15)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.qlMessage = QtGui.QLabel(self.frame)
        self.qlMessage.setGeometry(QtCore.QRect(260, 20, 591, 16))
        self.qlMessage.setObjectName("qlMessage")
        self.actionCopy = QtGui.QAction(mainDialog)
        self.actionCopy.setObjectName("actionCopy")

        self.retranslateUi(mainDialog)
        QtCore.QMetaObject.connectSlotsByName(mainDialog)
        mainDialog.setTabOrder(self.comboBoxTech, self.comboBoxBand)
        mainDialog.setTabOrder(self.comboBoxBand, self.spinBoxPDMStart)
        mainDialog.setTabOrder(self.spinBoxPDMStart, self.spinBoxPDMEnd)
        mainDialog.setTabOrder(self.spinBoxPDMEnd, self.btnStartSweep)
        mainDialog.setTabOrder(self.btnStartSweep, self.btnHPM)
        mainDialog.setTabOrder(self.btnHPM, self.btnLPM)
        mainDialog.setTabOrder(self.btnLPM, self.btnTxOn)
        mainDialog.setTabOrder(self.btnTxOn, self.btnTxOff)
        mainDialog.setTabOrder(self.btnTxOff, self.btnChMinus)
        mainDialog.setTabOrder(self.btnChMinus, self.btnChPlus)
        mainDialog.setTabOrder(self.btnChPlus, self.btnPDMPlus)
        mainDialog.setTabOrder(self.btnPDMPlus, self.btnPDMMinus)

    def retranslateUi(self, mainDialog):
        mainDialog.setWindowTitle(QtGui.QApplication.translate("mainDialog", "RF Tuning Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxInfo.setTitle(QtGui.QApplication.translate("mainDialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.qlTech.setText(QtGui.QApplication.translate("mainDialog", "Technology", None, QtGui.QApplication.UnicodeUTF8))
        self.qlBand.setText(QtGui.QApplication.translate("mainDialog", "Band", None, QtGui.QApplication.UnicodeUTF8))
        self.qlDLchTitle.setText(QtGui.QApplication.translate("mainDialog", "DL channel", None, QtGui.QApplication.UnicodeUTF8))
        self.qlULchTitle.setText(QtGui.QApplication.translate("mainDialog", "UL channel", None, QtGui.QApplication.UnicodeUTF8))
        self.qlPDMTitle.setText(QtGui.QApplication.translate("mainDialog", "PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.qlSMPSTitle.setText(QtGui.QApplication.translate("mainDialog", "SMPS", None, QtGui.QApplication.UnicodeUTF8))
        self.qlBWTitle.setText(QtGui.QApplication.translate("mainDialog", "Bandwidth", None, QtGui.QApplication.UnicodeUTF8))
        self.qlBW.setText(QtGui.QApplication.translate("mainDialog", "5MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.qlDLch.setText(QtGui.QApplication.translate("mainDialog", "10700", None, QtGui.QApplication.UnicodeUTF8))
        self.qlULch.setText(QtGui.QApplication.translate("mainDialog", "9750", None, QtGui.QApplication.UnicodeUTF8))
        self.qlPDM.setText(QtGui.QApplication.translate("mainDialog", "85", None, QtGui.QApplication.UnicodeUTF8))
        self.qlSMPS.setText(QtGui.QApplication.translate("mainDialog", "3700", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSweep.setTitle(QtGui.QApplication.translate("mainDialog", "Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.qlSweepPDMStart.setText(QtGui.QApplication.translate("mainDialog", "Start PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.qlSweepPDMEnd.setText(QtGui.QApplication.translate("mainDialog", "End PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStartSweep.setText(QtGui.QApplication.translate("mainDialog", "Start Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChMinus.setText(QtGui.QApplication.translate("mainDialog", "-ch", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChMinus.setShortcut(QtGui.QApplication.translate("mainDialog", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPDMPlus.setText(QtGui.QApplication.translate("mainDialog", "+PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPDMPlus.setShortcut(QtGui.QApplication.translate("mainDialog", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChPlus.setText(QtGui.QApplication.translate("mainDialog", "+ch", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChPlus.setShortcut(QtGui.QApplication.translate("mainDialog", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPDMMinus.setText(QtGui.QApplication.translate("mainDialog", "-PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPDMMinus.setShortcut(QtGui.QApplication.translate("mainDialog", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxMisc.setTitle(QtGui.QApplication.translate("mainDialog", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.qlGPIBTitle.setText(QtGui.QApplication.translate("mainDialog", "Callbox GPIB", None, QtGui.QApplication.UnicodeUTF8))
        self.qlCOMTitle.setText(QtGui.QApplication.translate("mainDialog", "Phone COM", None, QtGui.QApplication.UnicodeUTF8))
        self.qlGPIB.setText(QtGui.QApplication.translate("mainDialog", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.qlCOM.setText(QtGui.QApplication.translate("mainDialog", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.qlGPIBTitle_2.setText(QtGui.QApplication.translate("mainDialog", "Power Supply", None, QtGui.QApplication.UnicodeUTF8))
        self.qlGPIB_2.setText(QtGui.QApplication.translate("mainDialog", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHPM.setText(QtGui.QApplication.translate("mainDialog", "HPM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLPM.setText(QtGui.QApplication.translate("mainDialog", "LPM", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTxOff.setText(QtGui.QApplication.translate("mainDialog", "Tx OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTxOn.setText(QtGui.QApplication.translate("mainDialog", "Tx ON", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("mainDialog", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("mainDialog", "Tx power", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("mainDialog", "PDM", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("mainDialog", "Max curr", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("mainDialog", "min curr", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("mainDialog", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("mainDialog", "-5MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("mainDialog", "+5MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("mainDialog", "EURTA-1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("mainDialog", "EUTRA+1", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 0).setText(QtGui.QApplication.translate("mainDialog", "9750", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.qlMessage.setText(QtGui.QApplication.translate("mainDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("mainDialog", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("mainDialog", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))

import icon_rc
